// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: data/protos/common.proto

package common_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangeScope int32

const (
	RangeScope_RANGE_ALL   RangeScope = 0 // 含左右
	RangeScope_RANGE_LEFT  RangeScope = 1 // 含左
	RangeScope_RANGE_RIGHT RangeScope = 2 // 含右
)

// Enum value maps for RangeScope.
var (
	RangeScope_name = map[int32]string{
		0: "RANGE_ALL",
		1: "RANGE_LEFT",
		2: "RANGE_RIGHT",
	}
	RangeScope_value = map[string]int32{
		"RANGE_ALL":   0,
		"RANGE_LEFT":  1,
		"RANGE_RIGHT": 2,
	}
)

func (x RangeScope) Enum() *RangeScope {
	p := new(RangeScope)
	*p = x
	return p
}

func (x RangeScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeScope) Descriptor() protoreflect.EnumDescriptor {
	return file_data_protos_common_proto_enumTypes[0].Descriptor()
}

func (RangeScope) Type() protoreflect.EnumType {
	return &file_data_protos_common_proto_enumTypes[0]
}

func (x RangeScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeScope.Descriptor instead.
func (RangeScope) EnumDescriptor() ([]byte, []int) {
	return file_data_protos_common_proto_rawDescGZIP(), []int{0}
}

type AccessStatus int32

const (
	AccessStatus_ACCESS_NORMAL    AccessStatus = 0 // 默认状态, 需要验证权限
	AccessStatus_ACCESS_ANONYMOUS AccessStatus = 1 // 可匿名访问，无需验证权限
	AccessStatus_ACCESS_DISABLED  AccessStatus = 2 // 已禁用，无需验证权限
)

// Enum value maps for AccessStatus.
var (
	AccessStatus_name = map[int32]string{
		0: "ACCESS_NORMAL",
		1: "ACCESS_ANONYMOUS",
		2: "ACCESS_DISABLED",
	}
	AccessStatus_value = map[string]int32{
		"ACCESS_NORMAL":    0,
		"ACCESS_ANONYMOUS": 1,
		"ACCESS_DISABLED":  2,
	}
)

func (x AccessStatus) Enum() *AccessStatus {
	p := new(AccessStatus)
	*p = x
	return p
}

func (x AccessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_protos_common_proto_enumTypes[1].Descriptor()
}

func (AccessStatus) Type() protoreflect.EnumType {
	return &file_data_protos_common_proto_enumTypes[1]
}

func (x AccessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessStatus.Descriptor instead.
func (AccessStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_protos_common_proto_rawDescGZIP(), []int{1}
}

type AccessMethod int32

const (
	AccessMethod_ACCESS_METHOD_GET     AccessMethod = 0
	AccessMethod_ACCESS_METHOD_HEAD    AccessMethod = 1
	AccessMethod_ACCESS_METHOD_POST    AccessMethod = 2
	AccessMethod_ACCESS_METHOD_PUT     AccessMethod = 3
	AccessMethod_ACCESS_METHOD_PATCH   AccessMethod = 4
	AccessMethod_ACCESS_METHOD_DELETE  AccessMethod = 5
	AccessMethod_ACCESS_METHOD_CONNECT AccessMethod = 6
	AccessMethod_ACCESS_METHOD_OPTIONS AccessMethod = 7
	AccessMethod_ACCESS_METHOD_TRACE   AccessMethod = 8
)

// Enum value maps for AccessMethod.
var (
	AccessMethod_name = map[int32]string{
		0: "ACCESS_METHOD_GET",
		1: "ACCESS_METHOD_HEAD",
		2: "ACCESS_METHOD_POST",
		3: "ACCESS_METHOD_PUT",
		4: "ACCESS_METHOD_PATCH",
		5: "ACCESS_METHOD_DELETE",
		6: "ACCESS_METHOD_CONNECT",
		7: "ACCESS_METHOD_OPTIONS",
		8: "ACCESS_METHOD_TRACE",
	}
	AccessMethod_value = map[string]int32{
		"ACCESS_METHOD_GET":     0,
		"ACCESS_METHOD_HEAD":    1,
		"ACCESS_METHOD_POST":    2,
		"ACCESS_METHOD_PUT":     3,
		"ACCESS_METHOD_PATCH":   4,
		"ACCESS_METHOD_DELETE":  5,
		"ACCESS_METHOD_CONNECT": 6,
		"ACCESS_METHOD_OPTIONS": 7,
		"ACCESS_METHOD_TRACE":   8,
	}
)

func (x AccessMethod) Enum() *AccessMethod {
	p := new(AccessMethod)
	*p = x
	return p
}

func (x AccessMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_data_protos_common_proto_enumTypes[2].Descriptor()
}

func (AccessMethod) Type() protoreflect.EnumType {
	return &file_data_protos_common_proto_enumTypes[2]
}

func (x AccessMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessMethod.Descriptor instead.
func (AccessMethod) EnumDescriptor() ([]byte, []int) {
	return file_data_protos_common_proto_rawDescGZIP(), []int{2}
}

type Pager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`       // 页码
	Size     int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`         // 数量
	Count    int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`       // 总数量
	Disabled bool  `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"` // 禁用分页
}

func (x *Pager) Reset() {
	*x = Pager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_protos_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_data_protos_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_data_protos_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pager) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Pager) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pager) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Pager) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RangeI64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  int64      `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`                   // 区间左
	Right int64      `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`                 // 区间右
	Scope RangeScope `protobuf:"varint,3,opt,name=scope,proto3,enum=RangeScope" json:"scope,omitempty"` // 应用范围
}

func (x *RangeI64) Reset() {
	*x = RangeI64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_protos_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeI64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeI64) ProtoMessage() {}

func (x *RangeI64) ProtoReflect() protoreflect.Message {
	mi := &file_data_protos_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeI64.ProtoReflect.Descriptor instead.
func (*RangeI64) Descriptor() ([]byte, []int) {
	return file_data_protos_common_proto_rawDescGZIP(), []int{1}
}

func (x *RangeI64) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *RangeI64) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *RangeI64) GetScope() RangeScope {
	if x != nil {
		return x.Scope
	}
	return RangeScope_RANGE_ALL
}

var File_data_protos_common_proto protoreflect.FileDescriptor

var file_data_protos_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x05, 0x50, 0x61,
	0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22,
	0x57, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x2a, 0x3c, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f,
	0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4c,
	0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x52,
	0x49, 0x47, 0x48, 0x54, 0x10, 0x02, 0x2a, 0x4c, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x5f, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x5f, 0x41, 0x4e, 0x4f, 0x4e, 0x59, 0x4d, 0x4f, 0x55, 0x53, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x2a, 0xee, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f,
	0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12,
	0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x48, 0x45,
	0x41, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d,
	0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x50, 0x55,
	0x54, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45,
	0x54, 0x48, 0x4f, 0x44, 0x5f, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14,
	0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10,
	0x06, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45, 0x54, 0x48,
	0x4f, 0x44, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x07, 0x12, 0x17, 0x0a, 0x13,
	0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x52,
	0x41, 0x43, 0x45, 0x10, 0x08, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x69, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_protos_common_proto_rawDescOnce sync.Once
	file_data_protos_common_proto_rawDescData = file_data_protos_common_proto_rawDesc
)

func file_data_protos_common_proto_rawDescGZIP() []byte {
	file_data_protos_common_proto_rawDescOnce.Do(func() {
		file_data_protos_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_protos_common_proto_rawDescData)
	})
	return file_data_protos_common_proto_rawDescData
}

var file_data_protos_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_data_protos_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_protos_common_proto_goTypes = []interface{}{
	(RangeScope)(0),   // 0: RangeScope
	(AccessStatus)(0), // 1: AccessStatus
	(AccessMethod)(0), // 2: AccessMethod
	(*Pager)(nil),     // 3: Pager
	(*RangeI64)(nil),  // 4: RangeI64
}
var file_data_protos_common_proto_depIdxs = []int32{
	0, // 0: RangeI64.scope:type_name -> RangeScope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_protos_common_proto_init() }
func file_data_protos_common_proto_init() {
	if File_data_protos_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_protos_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_protos_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeI64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_protos_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_protos_common_proto_goTypes,
		DependencyIndexes: file_data_protos_common_proto_depIdxs,
		EnumInfos:         file_data_protos_common_proto_enumTypes,
		MessageInfos:      file_data_protos_common_proto_msgTypes,
	}.Build()
	File_data_protos_common_proto = out.File
	file_data_protos_common_proto_rawDesc = nil
	file_data_protos_common_proto_goTypes = nil
	file_data_protos_common_proto_depIdxs = nil
}
