definitions:
  common.ReplyHeader:
    properties:
      code:
        $ref: '#/definitions/ecode.ECode'
      message:
        type: string
      trace_id:
        type: integer
    type: object
  create.Params:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  ecode.ECode:
    enum:
    - 0
    - 400000
    - 400001
    - 400002
    - 400003
    - 400004
    - 401001
    - 401002
    - 401003
    - 431000
    - 431001
    - 431002
    - 431003
    - 431004
    - 431005
    - 431006
    - 431007
    - 431008
    - 500000
    - 500001
    - 510001
    - 510002
    - 510003
    - 511001
    - 511002
    - 511003
    - 512001
    - 512002
    - 512003
    - 513001
    - 513002
    - 513003
    - 514001
    - 514002
    - 514003
    - 515001
    - 515002
    - 515003
    type: integer
    x-enum-comments:
      ECode_ACCESS_Disabled: 接口已禁用
      ECode_ACCESS_Forbidden: 没有访问权限
      ECode_AUTH_TOKEN_Expired: token过期
      ECode_AUTH_TOKEN_Invalid: 无效Token
      ECode_AUTH_TOKEN_NotFound: token不存在
      ECode_AUTH_TOKEN_Required: 账户未登录
      ECode_BAD_REQUEST: 请求异常
      ECode_INVALID_PARAMS: 参数异常
      ECode_SUCCESS: 默认无错误
      ECode_SYSTEM_ERROR_Unimplemented: 功能未实现
      ECode_SYSTEM_INTERNAL_ERROR: 服务异常
    x-enum-varnames:
    - ECode_SUCCESS
    - ECode_BAD_REQUEST
    - ECode_AUTH_TOKEN_Required
    - ECode_AUTH_TOKEN_Invalid
    - ECode_AUTH_TOKEN_NotFound
    - ECode_AUTH_TOKEN_Expired
    - ECode_ACCESS_NotFound
    - ECode_ACCESS_Forbidden
    - ECode_ACCESS_Disabled
    - ECode_INVALID_PARAMS
    - ECode_USER_PARAMS_ERROR_NameRequired
    - ECode_USER_PARAMS_ERROR_UsernameRequired
    - ECode_USER_PARAMS_ERROR_PasswordRequired
    - ECode_USER_PARAMS_ERROR_UsernameExist
    - ECode_USER_PARAMS_ERROR_UserNotFound
    - ECode_USER_PARAMS_ERROR_NameInvalid
    - ECode_USER_PARAMS_ERROR_UsernameInvalid
    - ECode_USER_PARAMS_ERROR_PasswordInvalid
    - ECode_SYSTEM_INTERNAL_ERROR
    - ECode_SYSTEM_ERROR_Unimplemented
    - ECode_AUTH_SERVICE_ERROR_ListAccess
    - ECode_AUTH_SERVICE_ERROR_OperateAccess
    - ECode_AUTH_SERVICE_ERROR_BatchOperateAccess
    - ECode_AUTH_SERVICE_ERROR_ListAuthToken
    - ECode_AUTH_SERVICE_ERROR_OperateAuthToken
    - ECode_AUTH_SERVICE_ERROR_BatchOperateAuthToken
    - ECode_AUTH_SERVICE_ERROR_ListUser
    - ECode_AUTH_SERVICE_ERROR_OperateUser
    - ECode_AUTH_SERVICE_ERROR_BatchOperateUser
    - ECode_AUTH_SERVICE_ERROR_ListRole
    - ECode_AUTH_SERVICE_ERROR_OperateRole
    - ECode_AUTH_SERVICE_ERROR_BatchOperateRole
    - ECode_AUTH_SERVICE_ERROR_ListUserRoleRef
    - ECode_AUTH_SERVICE_ERROR_OperateUserRoleRef
    - ECode_AUTH_SERVICE_ERROR_BatchOperateUserRoleRef
    - ECode_AUTH_SERVICE_ERROR_ListPermission
    - ECode_AUTH_SERVICE_ERROR_OperatePermission
    - ECode_AUTH_SERVICE_ERROR_BatchOperatePermission
  info.Params:
    type: object
  login.Params:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  refresh.Params:
    properties:
      refresh_token:
        type: string
    type: object
  system.Response:
    properties:
      data: {}
      header:
        $ref: '#/definitions/common.ReplyHeader'
    type: object
host: localhost:18000
info:
  contact:
    email: 3940422@qq.com
    name: atopx
    url: https://github.com/atopx/superserver.git
  description: 集成网盘、多媒体、Webdav、服务器监控等一体的超级服务器后台
  title: superserver
  version: 0.1.0
paths:
  /api/basic/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: ping
      tags:
      - Basic
  /api/user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/create.Params'
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功
          schema:
            $ref: '#/definitions/system.Response'
      summary: 用户注册
      tags:
      - 用户
  /api/user/info:
    get:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/info.Params'
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功
          schema:
            $ref: '#/definitions/system.Response'
      summary: 用户详情
      tags:
      - 用户
  /api/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/login.Params'
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功
          schema:
            $ref: '#/definitions/system.Response'
      summary: 用户登录
      tags:
      - 用户
  /api/user/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/refresh.Params'
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功
          schema:
            $ref: '#/definitions/system.Response'
      summary: 用户刷新AccessToken
      tags:
      - 用户
swagger: "2.0"
