// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: data/protos/novel.proto

package novel_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NovelStatus int32

const (
	NovelStatus_NOVEL_NONE     NovelStatus = 0
	NovelStatus_NOVEL_ENABLED  NovelStatus = 1 // 启用监控
	NovelStatus_NOVEL_DISABLED NovelStatus = 2 // 手动禁止监控
	NovelStatus_NOVEL_SUCCESS  NovelStatus = 3 // 连续N次未发生变化，停止监控
	NovelStatus_NOVEL_ERROR    NovelStatus = 4 // 连续N次错误, 停止监控
)

// Enum value maps for NovelStatus.
var (
	NovelStatus_name = map[int32]string{
		0: "NOVEL_NONE",
		1: "NOVEL_ENABLED",
		2: "NOVEL_DISABLED",
		3: "NOVEL_SUCCESS",
		4: "NOVEL_ERROR",
	}
	NovelStatus_value = map[string]int32{
		"NOVEL_NONE":     0,
		"NOVEL_ENABLED":  1,
		"NOVEL_DISABLED": 2,
		"NOVEL_SUCCESS":  3,
		"NOVEL_ERROR":    4,
	}
)

func (x NovelStatus) Enum() *NovelStatus {
	p := new(NovelStatus)
	*p = x
	return p
}

func (x NovelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NovelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_protos_novel_proto_enumTypes[0].Descriptor()
}

func (NovelStatus) Type() protoreflect.EnumType {
	return &file_data_protos_novel_proto_enumTypes[0]
}

func (x NovelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NovelStatus.Descriptor instead.
func (NovelStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_protos_novel_proto_rawDescGZIP(), []int{0}
}

type ScanStatus int32

const (
	ScanStatus_SCAN_NONE    ScanStatus = 0
	ScanStatus_SCAN_PENDING ScanStatus = 1
	ScanStatus_SCAN_RUNNING ScanStatus = 2
	ScanStatus_SCAN_SUCCESS ScanStatus = 3
	ScanStatus_SCAN_ERROR   ScanStatus = 4
)

// Enum value maps for ScanStatus.
var (
	ScanStatus_name = map[int32]string{
		0: "SCAN_NONE",
		1: "SCAN_PENDING",
		2: "SCAN_RUNNING",
		3: "SCAN_SUCCESS",
		4: "SCAN_ERROR",
	}
	ScanStatus_value = map[string]int32{
		"SCAN_NONE":    0,
		"SCAN_PENDING": 1,
		"SCAN_RUNNING": 2,
		"SCAN_SUCCESS": 3,
		"SCAN_ERROR":   4,
	}
)

func (x ScanStatus) Enum() *ScanStatus {
	p := new(ScanStatus)
	*p = x
	return p
}

func (x ScanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_protos_novel_proto_enumTypes[1].Descriptor()
}

func (ScanStatus) Type() protoreflect.EnumType {
	return &file_data_protos_novel_proto_enumTypes[1]
}

func (x ScanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanStatus.Descriptor instead.
func (ScanStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_protos_novel_proto_rawDescGZIP(), []int{1}
}

var File_data_protos_novel_proto protoreflect.FileDescriptor

var file_data_protos_novel_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x6f,
	0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x68, 0x0a, 0x0b, 0x4e, 0x6f, 0x76,
	0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x56, 0x45,
	0x4c, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x56, 0x45,
	0x4c, 0x5f, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4e,
	0x4f, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x04, 0x2a, 0x61, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x42, 0x1e, 0x5a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x5f, 0x69, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_protos_novel_proto_rawDescOnce sync.Once
	file_data_protos_novel_proto_rawDescData = file_data_protos_novel_proto_rawDesc
)

func file_data_protos_novel_proto_rawDescGZIP() []byte {
	file_data_protos_novel_proto_rawDescOnce.Do(func() {
		file_data_protos_novel_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_protos_novel_proto_rawDescData)
	})
	return file_data_protos_novel_proto_rawDescData
}

var file_data_protos_novel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_protos_novel_proto_goTypes = []interface{}{
	(NovelStatus)(0), // 0: NovelStatus
	(ScanStatus)(0),  // 1: ScanStatus
}
var file_data_protos_novel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_protos_novel_proto_init() }
func file_data_protos_novel_proto_init() {
	if File_data_protos_novel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_protos_novel_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_protos_novel_proto_goTypes,
		DependencyIndexes: file_data_protos_novel_proto_depIdxs,
		EnumInfos:         file_data_protos_novel_proto_enumTypes,
	}.Build()
	File_data_protos_novel_proto = out.File
	file_data_protos_novel_proto_rawDesc = nil
	file_data_protos_novel_proto_goTypes = nil
	file_data_protos_novel_proto_depIdxs = nil
}
