// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: public/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	ecode "superserver/domain/public/ecode"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangeScope int32

const (
	RangeScope_RANGE_ALL   RangeScope = 0 // 含左右
	RangeScope_RANGE_LEFT  RangeScope = 1 // 含左
	RangeScope_RANGE_RIGHT RangeScope = 2 // 含右
)

// Enum value maps for RangeScope.
var (
	RangeScope_name = map[int32]string{
		0: "RANGE_ALL",
		1: "RANGE_LEFT",
		2: "RANGE_RIGHT",
	}
	RangeScope_value = map[string]int32{
		"RANGE_ALL":   0,
		"RANGE_LEFT":  1,
		"RANGE_RIGHT": 2,
	}
)

func (x RangeScope) Enum() *RangeScope {
	p := new(RangeScope)
	*p = x
	return p
}

func (x RangeScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeScope) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[0].Descriptor()
}

func (RangeScope) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[0]
}

func (x RangeScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeScope.Descriptor instead.
func (RangeScope) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{0}
}

type BooleanScope int32

const (
	BooleanScope_BOOL_ALL   BooleanScope = 0
	BooleanScope_BOOL_FALSE BooleanScope = 1
	BooleanScope_BOOL_TRUE  BooleanScope = 2
)

// Enum value maps for BooleanScope.
var (
	BooleanScope_name = map[int32]string{
		0: "BOOL_ALL",
		1: "BOOL_FALSE",
		2: "BOOL_TRUE",
	}
	BooleanScope_value = map[string]int32{
		"BOOL_ALL":   0,
		"BOOL_FALSE": 1,
		"BOOL_TRUE":  2,
	}
)

func (x BooleanScope) Enum() *BooleanScope {
	p := new(BooleanScope)
	*p = x
	return p
}

func (x BooleanScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BooleanScope) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[1].Descriptor()
}

func (BooleanScope) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[1]
}

func (x BooleanScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BooleanScope.Descriptor instead.
func (BooleanScope) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{1}
}

type SortDirection int32

const (
	SortDirection_SORT_ASC  SortDirection = 0
	SortDirection_SORT_DESC SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_ASC",
		1: "SORT_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_ASC":  0,
		"SORT_DESC": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{2}
}

type Operation int32

const (
	// 基础操作类型
	Operation_OPERATION_CREATE      Operation = 0
	Operation_OPERATION_UPDATE      Operation = 1
	Operation_OPERATION_DELETE      Operation = 2
	Operation_OPERATION_REAL_DELETE Operation = 3
	// 高阶操作类型
	Operation_OPERATION_UPSERT Operation = 101
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:   "OPERATION_CREATE",
		1:   "OPERATION_UPDATE",
		2:   "OPERATION_DELETE",
		3:   "OPERATION_REAL_DELETE",
		101: "OPERATION_UPSERT",
	}
	Operation_value = map[string]int32{
		"OPERATION_CREATE":      0,
		"OPERATION_UPDATE":      1,
		"OPERATION_DELETE":      2,
		"OPERATION_REAL_DELETE": 3,
		"OPERATION_UPSERT":      101,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[3].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[3]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{3}
}

type HttpMethod int32

const (
	HttpMethod_GET     HttpMethod = 0 // 方法请求一个指定资源的表示形式，使用 GET 的请求应该只被用于获取数据
	HttpMethod_HEAD    HttpMethod = 1 // 方法请求一个与 GET 请求的响应相同的响应，但没有响应体
	HttpMethod_POST    HttpMethod = 2 // 方法用于将实体提交到指定的资源，通常导致在服务器上的状态变化或副作用
	HttpMethod_PUT     HttpMethod = 3 // 方法用请求有效载荷替换目标资源的所有当前表示
	HttpMethod_DELETE  HttpMethod = 4 // 方法删除指定的资源
	HttpMethod_CONNECT HttpMethod = 5 // 方法建立一个到由目标资源标识的服务器的隧道
	HttpMethod_OPTION  HttpMethod = 6 // 方法用于描述目标资源的通信选项
	HttpMethod_PATCH   HttpMethod = 7 // 方法用于对资源应用部分修改
	HttpMethod_TRACE   HttpMethod = 8 // 方法沿着到目标资源的路径执行一个消息环回测试
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "GET",
		1: "HEAD",
		2: "POST",
		3: "PUT",
		4: "DELETE",
		5: "CONNECT",
		6: "OPTION",
		7: "PATCH",
		8: "TRACE",
	}
	HttpMethod_value = map[string]int32{
		"GET":     0,
		"HEAD":    1,
		"POST":    2,
		"PUT":     3,
		"DELETE":  4,
		"CONNECT": 5,
		"OPTION":  6,
		"PATCH":   7,
		"TRACE":   8,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[4].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[4]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{4}
}

type HttpProtocol int32

const (
	HttpProtocol_HTTP  HttpProtocol = 0 // http
	HttpProtocol_HTTPS HttpProtocol = 1 // https
	HttpProtocol_GRPC  HttpProtocol = 2 // http/2.0
	HttpProtocol_WS    HttpProtocol = 3 // websocket
	HttpProtocol_WSS   HttpProtocol = 4 // websockets
)

// Enum value maps for HttpProtocol.
var (
	HttpProtocol_name = map[int32]string{
		0: "HTTP",
		1: "HTTPS",
		2: "GRPC",
		3: "WS",
		4: "WSS",
	}
	HttpProtocol_value = map[string]int32{
		"HTTP":  0,
		"HTTPS": 1,
		"GRPC":  2,
		"WS":    3,
		"WSS":   4,
	}
)

func (x HttpProtocol) Enum() *HttpProtocol {
	p := new(HttpProtocol)
	*p = x
	return p
}

func (x HttpProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_public_common_proto_enumTypes[5].Descriptor()
}

func (HttpProtocol) Type() protoreflect.EnumType {
	return &file_public_common_proto_enumTypes[5]
}

func (x HttpProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpProtocol.Descriptor instead.
func (HttpProtocol) EnumDescriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{5}
}

type Pager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`       // 页码
	Size     uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`         // 数量
	Count    uint64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`       // 总数量
	Disabled bool   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"` // 禁用分页
}

func (x *Pager) Reset() {
	*x = Pager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pager) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Pager) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pager) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Pager) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RangeI64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  int64      `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`                          // 区间左
	Right int64      `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`                        // 区间右
	Scope RangeScope `protobuf:"varint,3,opt,name=scope,proto3,enum=public.RangeScope" json:"scope,omitempty"` // 应用范围
}

func (x *RangeI64) Reset() {
	*x = RangeI64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeI64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeI64) ProtoMessage() {}

func (x *RangeI64) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeI64.ProtoReflect.Descriptor instead.
func (*RangeI64) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{1}
}

func (x *RangeI64) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *RangeI64) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *RangeI64) GetScope() RangeScope {
	if x != nil {
		return x.Scope
	}
	return RangeScope_RANGE_ALL
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId  int64  `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Operator int32  `protobuf:"varint,3,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetTraceId() int64 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *Header) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Header) GetOperator() int32 {
	if x != nil {
		return x.Operator
	}
	return 0
}

type ReplyHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId int64       `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Code    ecode.ECode `protobuf:"varint,2,opt,name=code,proto3,enum=public.ECode" json:"code,omitempty"`
	Message string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReplyHeader) Reset() {
	*x = ReplyHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyHeader) ProtoMessage() {}

func (x *ReplyHeader) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyHeader.ProtoReflect.Descriptor instead.
func (*ReplyHeader) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyHeader) GetTraceId() int64 {
	if x != nil {
		return x.TraceId
	}
	return 0
}

func (x *ReplyHeader) GetCode() ecode.ECode {
	if x != nil {
		return x.Code
	}
	return ecode.ECode(0)
}

func (x *ReplyHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BetweenInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scope RangeScope `protobuf:"varint,1,opt,name=scope,proto3,enum=public.RangeScope" json:"scope,omitempty"`
	Left  int64      `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Right int64      `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *BetweenInt64) Reset() {
	*x = BetweenInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetweenInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetweenInt64) ProtoMessage() {}

func (x *BetweenInt64) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetweenInt64.ProtoReflect.Descriptor instead.
func (*BetweenInt64) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{4}
}

func (x *BetweenInt64) GetScope() RangeScope {
	if x != nil {
		return x.Scope
	}
	return RangeScope_RANGE_ALL
}

func (x *BetweenInt64) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *BetweenInt64) GetRight() int64 {
	if x != nil {
		return x.Right
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field     string        `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction SortDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=public.SortDirection" json:"direction,omitempty"`
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{5}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_ASC
}

type HttpHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_public_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeader.ProtoReflect.Descriptor instead.
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return file_public_common_proto_rawDescGZIP(), []int{6}
}

func (x *HttpHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HttpHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_public_common_proto protoreflect.FileDescriptor

var file_public_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x1a, 0x12, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x63, 0x0a, 0x05, 0x50, 0x61, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x5e, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x49,
	0x36, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x28, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x57, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x65, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x45, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x0c, 0x42, 0x65, 0x74, 0x77, 0x65, 0x65,
	0x6e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x22, 0x51, 0x0a, 0x04, 0x53, 0x6f,
	0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x33, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a,
	0x0a, 0x48, 0x74, 0x74, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2a, 0x3c, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10,
	0x02, 0x2a, 0x3b, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x46, 0x41, 0x4c, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x54, 0x52, 0x55, 0x45, 0x10, 0x02, 0x2a, 0x2c,
	0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x41, 0x53, 0x43, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x2a, 0x7e, 0x0a, 0x09,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x41, 0x4c, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x53, 0x45, 0x52, 0x54, 0x10, 0x65, 0x2a, 0x6d, 0x0a, 0x0a,
	0x48, 0x74, 0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x07,
	0x12, 0x09, 0x0a, 0x05, 0x54, 0x52, 0x41, 0x43, 0x45, 0x10, 0x08, 0x2a, 0x3e, 0x0a, 0x0c, 0x48,
	0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x47, 0x52, 0x50, 0x43, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x57, 0x53,
	0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x53, 0x53, 0x10, 0x04, 0x42, 0x22, 0x5a, 0x20, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_common_proto_rawDescOnce sync.Once
	file_public_common_proto_rawDescData = file_public_common_proto_rawDesc
)

func file_public_common_proto_rawDescGZIP() []byte {
	file_public_common_proto_rawDescOnce.Do(func() {
		file_public_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_common_proto_rawDescData)
	})
	return file_public_common_proto_rawDescData
}

var file_public_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_public_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_public_common_proto_goTypes = []interface{}{
	(RangeScope)(0),      // 0: public.RangeScope
	(BooleanScope)(0),    // 1: public.BooleanScope
	(SortDirection)(0),   // 2: public.SortDirection
	(Operation)(0),       // 3: public.Operation
	(HttpMethod)(0),      // 4: public.HttpMethod
	(HttpProtocol)(0),    // 5: public.HttpProtocol
	(*Pager)(nil),        // 6: public.Pager
	(*RangeI64)(nil),     // 7: public.RangeI64
	(*Header)(nil),       // 8: public.Header
	(*ReplyHeader)(nil),  // 9: public.ReplyHeader
	(*BetweenInt64)(nil), // 10: public.BetweenInt64
	(*Sort)(nil),         // 11: public.Sort
	(*HttpHeader)(nil),   // 12: public.HttpHeader
	(ecode.ECode)(0),     // 13: public.ECode
}
var file_public_common_proto_depIdxs = []int32{
	0,  // 0: public.RangeI64.scope:type_name -> public.RangeScope
	13, // 1: public.ReplyHeader.code:type_name -> public.ECode
	0,  // 2: public.BetweenInt64.scope:type_name -> public.RangeScope
	2,  // 3: public.Sort.direction:type_name -> public.SortDirection
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_public_common_proto_init() }
func file_public_common_proto_init() {
	if File_public_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeI64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetweenInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_common_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_common_proto_goTypes,
		DependencyIndexes: file_public_common_proto_depIdxs,
		EnumInfos:         file_public_common_proto_enumTypes,
		MessageInfos:      file_public_common_proto_msgTypes,
	}.Build()
	File_public_common_proto = out.File
	file_public_common_proto_rawDesc = nil
	file_public_common_proto_goTypes = nil
	file_public_common_proto_depIdxs = nil
}
