//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub mod prelude;

pub mod access;
pub mod auth_token;
pub mod computer;
pub mod file;
pub mod folder;
pub mod label;
pub mod note;
pub mod note_label;
pub mod note_topic;
pub mod permission;
pub mod role;
pub mod user;
pub mod user_role_ref;
