//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude;

pub mod access;
pub mod auth_token;
pub mod computer;
pub mod permission;
pub mod role;
pub mod user;
pub mod user_role_ref;
