//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::access::Entity as Access;
pub use super::auth_token::Entity as AuthToken;
pub use super::book::Entity as Book;
pub use super::chapter::Entity as Chapter;
pub use super::label::Entity as Label;
pub use super::note::Entity as Note;
pub use super::note_label::Entity as NoteLabel;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role_ref::Entity as UserRoleRef;
