//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::access::Entity as Access;
pub use super::auth_token::Entity as AuthToken;
pub use super::computer::Entity as Computer;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role_ref::Entity as UserRoleRef;
