// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: novel/service.proto

package novel_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NovelService_ListBook_FullMethodName    = "/novel_service.NovelService/ListBook"
	NovelService_ListChapter_FullMethodName = "/novel_service.NovelService/ListChapter"
)

// NovelServiceClient is the client API for NovelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NovelServiceClient interface {
	ListBook(ctx context.Context, in *ListBookParams, opts ...grpc.CallOption) (*ListBookReply, error)
	ListChapter(ctx context.Context, in *ListChapterParams, opts ...grpc.CallOption) (*ListChapterReply, error)
}

type novelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNovelServiceClient(cc grpc.ClientConnInterface) NovelServiceClient {
	return &novelServiceClient{cc}
}

func (c *novelServiceClient) ListBook(ctx context.Context, in *ListBookParams, opts ...grpc.CallOption) (*ListBookReply, error) {
	out := new(ListBookReply)
	err := c.cc.Invoke(ctx, NovelService_ListBook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListChapter(ctx context.Context, in *ListChapterParams, opts ...grpc.CallOption) (*ListChapterReply, error) {
	out := new(ListChapterReply)
	err := c.cc.Invoke(ctx, NovelService_ListChapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovelServiceServer is the server API for NovelService service.
// All implementations must embed UnimplementedNovelServiceServer
// for forward compatibility
type NovelServiceServer interface {
	ListBook(context.Context, *ListBookParams) (*ListBookReply, error)
	ListChapter(context.Context, *ListChapterParams) (*ListChapterReply, error)
	mustEmbedUnimplementedNovelServiceServer()
}

// UnimplementedNovelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNovelServiceServer struct {
}

func (UnimplementedNovelServiceServer) ListBook(context.Context, *ListBookParams) (*ListBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBook not implemented")
}
func (UnimplementedNovelServiceServer) ListChapter(context.Context, *ListChapterParams) (*ListChapterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChapter not implemented")
}
func (UnimplementedNovelServiceServer) mustEmbedUnimplementedNovelServiceServer() {}

// UnsafeNovelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovelServiceServer will
// result in compilation errors.
type UnsafeNovelServiceServer interface {
	mustEmbedUnimplementedNovelServiceServer()
}

func RegisterNovelServiceServer(s grpc.ServiceRegistrar, srv NovelServiceServer) {
	s.RegisterService(&NovelService_ServiceDesc, srv)
}

func _NovelService_ListBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListBook(ctx, req.(*ListBookParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChapterParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListChapter(ctx, req.(*ListChapterParams))
	}
	return interceptor(ctx, in, info, handler)
}

// NovelService_ServiceDesc is the grpc.ServiceDesc for NovelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NovelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novel_service.NovelService",
	HandlerType: (*NovelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBook",
			Handler:    _NovelService_ListBook_Handler,
		},
		{
			MethodName: "ListChapter",
			Handler:    _NovelService_ListChapter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novel/service.proto",
}
